packages:
  - "."

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - canvas
  - esbuild
  - msgpackr-extract
  - sharp

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - studiocms
  - effectify
  - astro-embed
  - astro
  - "@astro-community/*"
  - "@astrojs/*"
  - "@studiocms/*"
  - "@withstudiocms/*"
  - "@lunariajs/core@0.2.0"
