packages:
  - '.'

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - canvas
  - esbuild
  - msgpackr-extract
  - sharp

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - studiocms
  - '@studiocms/*'
  - '@withstudiocms/*'