name: CI - Link Validator

on:
  pull_request:
    branches:
      - main

jobs:
  test-links:
    name: Run Starlight Link Check
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - name: Check out code using Git
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
  
      - name: Install Tools & Dependencies
        uses: withstudiocms/automations/.github/actions/install@main

      - name: Run Link Check
        run: CHECK_LINKS=true && pnpm ci:build
