name: CI - Translation Report Bot

on:
  schedule:
    - cron:  '0 10 * * TUE'
  workflow_dispatch:

jobs:
  translation:
    name: translation_report
    if: ${{ github.repository_owner == 'withstudiocms' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Install Tools & Dependencies
        uses: withstudiocms/automations/.github/actions/install@main

      - id: message
        name: Format Discord message
        run: pnpm ci:lunaria:report
        env:
          WORKFLOW_DISPATCH: ${{ github.event_name == 'workflow_dispatch' }}

      - name: Send a Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_I18N_REPORT }}
          DISCORD_EMBEDS: '[ { "title": "Translations Summary", "description": "See our [Translation Status page](<https://i18n.docs.studiocms.dev>) for more, including open PRs.", "image": { "url": "https://i18n.docs.studiocms.dev/summary.svg" } }]'
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "${{ steps.message.outputs.DISCORD_MESSAGE }}"
